import {
  RankedHook,
  ScriptItem,
  StoryboardFrame,
  VideoShotPrompt,
  AdVariant,
  ViralPlanOutput,
} from '@shared/types';

export function generateCreativeBriefMarkdown(params: {
  painPoint: string;
  audience: string;
  language: string;
  topHooks: RankedHook[];
  primaryScript: ScriptItem;
  storyboard: StoryboardFrame[];
  videoPrompts: VideoShotPrompt[];
}): string {
  const { painPoint, audience, language, topHooks, primaryScript, storyboard, videoPrompts } = params;

  return `# Growth Creative Brief — MySivi Growth Lab

## Campaign Overview
- **Learner Pain Point:** "${painPoint}"
- **Target Persona:** ${audience}
- **Language / Script:** ${language}
- **AI Persona:** Arya (Warm, zero-judgment conversational tutor)
- **Primary Deliverable:** 15-second High-Retention Vertical Video (Instagram Reel / YouTube Short)

---

## Top Evaluated Hooks (Weighted Algorithm Rank)
${topHooks
  .slice(0, 3)
  .map(
    (h, i) =>
      `${i + 1}. **"${h.displayText}"** (Score: ${h.weightedScore}/10)\n   *Why it works:* ${h.critique}\n   *Compliance:* ${
        h.compliance.isCompliant ? '✓ Passed all brand safety checks' : '⚠️ Rewritten for safety'
      }`
  )
  .join('\n\n')}

---

## 15-Second Video Script: "${primaryScript.hookText}"
**Total Runtime:** 15 Seconds  
**Audio Vibe:** ${primaryScript.beats[0]?.audioVibe || 'Natural, warm'}

${primaryScript.beats
  .map(
    (beat) => `### Beat ${beat.timecode} — ${beat.name}
- **Voiceover:** "${beat.voiceover}"
- **On-Screen Caption:** "${beat.caption}"
- **Visual Direction:** ${beat.visual}
- **Audio Vibe:** ${beat.audioVibe}
`
  )
  .join('\n')}

**Call to Action:** "${primaryScript.cta}"

---

## Storyboard Frames (Visual Direction)
${storyboard
  .map(
    (f) => `### Frame ${f.frameIndex} (${f.timecode})
- **Scene:** ${f.sceneDescription}
- **Image Generation Prompt:** \`${f.imagePrompt}\`
- **Accessibility Alt:** ${f.altText}
`
  )
  .join('\n')}

---

## Generative Video Prompts (Veo / Runway Gen-3 / Kling)
${videoPrompts
  .map(
    (p) => `### ${p.shot}
- **Camera:** ${p.camera}
- **Lighting:** ${p.lighting}
- **Motion:** ${p.motion}
- **Duration:** ${p.duration}
- **Prompt:**
  \`\`\`
  ${p.prompt}
  \`\`\`
- **Negative Prompt:** \`${p.negativePrompt}\`
`
  )
  .join('\n')}

---
*Generated by Growth Lab — AI Growth Operating System for MySivi.*
`;
}

export function generateVideoPromptsText(prompts: VideoShotPrompt[]): string {
  return prompts
    .map(
      (p) => `// ${p.shot} (${p.duration})
PROMPT:
${p.prompt}

NEGATIVE PROMPT:
${p.negativePrompt}

CAMERA: ${p.camera}
LIGHTING: ${p.lighting}
MOTION: ${p.motion}
--------------------------------------------------`
    )
    .join('\n\n');
}

export function downloadJsonFile(data: unknown, filename: string): void {
  const jsonStr = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function generateAdsBriefMarkdown(variants: AdVariant[]): string {
  return `# Meta Ads Matrix Brief — MySivi Growth Lab

${variants
  .map(
    (v, i) => `## Variant ${i + 1}: ${v.variantName}
- **Target Audience:** ${v.audience}
- **Strategic Angle:** ${v.angle}
- **Hook:** "${v.hook}"
- **Primary Text (${v.primaryText.length} chars):** ${v.primaryText}
- **Headline (${v.headline.length} chars):** ${v.headline}
- **Description (${v.description.length} chars):** ${v.description}
- **CTA:** ${v.ctaType}
`
  )
  .join('\n---\n\n')}
`;
}

export function generateViralPlanMarkdown(plan: ViralPlanOutput): string {
  return `# 7-Day Organic Viral Growth Plan — MySivi Growth Lab

## Trend Adaptation: "${plan.trendDescription}"

${plan.trendAdaptations
  .map(
    (a, i) => `### Concept ${i + 1}
- **Original Format:** ${a.originalFormat}
- **MySivi Angle:** ${a.mysiviAdaptation}
- **Hook:** "${a.hook}"
- **Beats:**
  ${a.beats.map((b) => `* ${b}`).join('\n  ')}
- **CTA / Comment Prompt:** "${a.cta}"
`
  )
  .join('\n')}

---

## 7-Day Multi-Format Content Calendar
${plan.calendar
  .map(
    (c) => `### Day ${c.day} (${c.dayName}) — [${c.format}]
- **Pillar:** ${c.pillar}
- **Topic:** ${c.topic}
- **Hook / Title:** "${c.hookOrHeadline}"
- **Algorithm Seed Comment:** "${c.firstCommentPrompt}"
`
  )
  .join('\n')}

---

## Creator Program Briefs ("Become a Creator")
${plan.creatorBriefs
  .map(
    (b) => `### ${b.title}
- **Target Persona:** ${b.creatorPersona}
- **Deliverables:** ${b.deliverables}
- **Dos:**
  ${b.dos.map((d) => `✓ ${d}`).join('\n  ')}
- **Don'ts:**
  ${b.donts.map((d) => `✗ ${d}`).join('\n  ')}
- **Brand Voice:** ${b.brandVoiceNotes}
`
  )
  .join('\n')}
`;
}
